### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by pacharanero** [leigh-hackspace/leigh-hackspace.github.io#1]
website needs a favicon. I have one somewhere, we can add this sometime in next few days @alexhartley

**Comment by awilkins** [comment]
Someone gimme the SVG of the hackspace icon and I'll make a multi-size one with all the bells and whistles.

**Comment by pacharanero** [comment]
[hackspace_logos.zip](https://github.com/leigh-hackspace/leigh-hackspace.github.io/files/165629/hackspace_logos.zip)

**Comment by awilkins** [comment]
```
for SIZE in 16 24 32 64 ; do inkscape -z -e hslogo-$SIZE.png -w $SIZE -h $SIZE \!HackspaceLogoHiRes.svg ; done
icotool -c hslogo-*.png -o hslogo.ico
```

[hslogo.ico.zip](https://github.com/leigh-hackspace/leigh-hackspace.github.io/files/165647/hslogo.ico.zip)

**Comment by awilkins** [comment]
Added favicon to site root
