### ISSUE TITLE
website font not the same as the previous site

### ISSUE THREAD

**Issue by pacharanero** [leigh-hackspace/leigh-hackspace.github.io#2]
need to change font to similar to previous site. I can't actually remember what it was before. We could alternatively use Transport, if we can find a version with a full character set.

**Comment by alexhartley** [comment]
The old one was lato.

**Comment by pacharanero** [comment]
cool. let's use that, it's a nice open source font.

weird;y we're thinking about using it for the whole of NHS.UK Alpha, we're
in the position of possibly being able to shift the NHS away from Frutiger
(£750,000 per year to licence) to Lato (free)

M

**Comment by awilkins** [comment]
Think you've got some jam stuck in your keyboard under the zero there...

Seriously?!? I've seen the branding guidelines (I've probably got a copy somewhere if you want them), had no idea they cost that much. Are we paying out a shedload to Pantone to use the names of the standard colours as well?

**Comment by pacharanero** [comment]
seriously. £750K pa is what the NHS pays for Frutiger

**Comment by adamprescott** [comment]
That's equivalent to how many Junior Doctors wages?

**Comment by awilkins** [comment]
Between 10 and 20.

**Comment by pacharanero** [comment]
based on JD starting salary of £22,636 we're looking at *over 30 *junior
doctors

M
